Theano/libgpuarray

- src/gpuarray_buffer_opencl.c
On some OpenCL GPUs, an exception, "pygpu.gpuarray.GpuArrayException: Invalid value", is thrown when initializing a GpuContext.
$ python -c "import pygpu; print pygpu.init('opencl0:1').devname"
Traceback (most recent call last):
File "<string>", line 1, in <module>
File "pygpu/gpuarray.pyx", line 587, in pygpu.gpuarray.init (pygpu/gpuarray.c:7506)
File "pygpu/gpuarray.pyx", line 558, in pygpu.gpuarray.pygpu_init (pygpu/gpuarray.c:7435)
File "pygpu/gpuarray.pyx", line 962, in pygpu.gpuarray.GpuContext.__cinit__ (pygpu/gpuarray.c:11098)
pygpu.gpuarray.GpuArrayException: Invalid value
This seems to occur because the driver_version buffer is not big enough to accommodate long device driver string signatures. 
When the following OpenCL function is called
```C
err = clGetDeviceInfo(id, …
```
> Fix OpenCL CL_DRIVER_VERSION query from causing GPU selection to fail.

- src/util/halloc.c
Not all instances of magic within src/util/halloc.c are protected by by the DEBUG macro; this PR resolves that.
> Fix non-debug builds.

- src/util/halloc.c
GCC 5 enables C11 by default, and stddef already creates struct max_align and max_align_t.
In order to compile libgpuarray you can either disable C11/C++11 on the CMakeLists (undesirable IMHO), or avoid redeclaring the struct if it has already been declared. This patch does just that. I decided not to remove the struct declaration altogether, in order to keep the support for older versions of the standard.
> Fix compilation with C11 or C++11 enabled (default on GCC 5).

- pygpu/gpuarray.pyx
- pygpu/tools.py
Hi, here are two small changes:
- in gpuarray.pyx, allow arrays to be created like empty(shape, dtype=numpy.float32).
- in tools.py, fix a bug that was throwing an exception if a binary function had a scalar and a vector argument.
> Two small fixes

- pygpu/elemwise.py
Hi, another small fix -- one of the kernels was causing nvcc to give a warning about tmp being declared but not used. Thanks!
> remove warning about unused variable tmp

- pygpu/elemwise.py
- pygpu/tests/test_tools.py
- pygpu/tools.py
Hi, the first two commits fix bugs in check_args that are described in the commit messages. The third commit is just a suggestion: this function computes information that never gets used in the contiguous case (which is presumably also the most common), so a simplified version check_contig only computes what is needed, and is faster.
> Two fixes and a suggestion for check_args()

- pygpu/reduction.py
Hi, in `reduction.py`, `ReductionKernel._get_basic_kernel` is cached according to its arguments `maxls` and `nd`, where `maxls` is the smaller of the reduction size and `self.init_local_size` (= 1024 on my machine). If there are a lot of small reductions, there will be many different versions of the basic kernel in the cache, too many to fit in the cache. However, one of the first things that the basic kernel does is to round `maxls` up to the nearest power of two. This patch does the rounding up before caching so that there are at most lg(self.init_local_size) different versions of the basic kernel for each value of `nd`. (It also does the rounding again afterwards, to avoid breaking anything.) I think this fixes the problem with small reductions without costing anything for larger …
> round reduction size up to nearest power of two to avoid overloading cache

- pygpu/tests/test_blas.py
This is encountered when scipy is not present.
#83
> Add missing SkipTest import

- src/gpuarray_buffer_cuda.c
- src/private_cuda.h
Tests have assured me that we don't need to wait on the host side
after a transfer in either direction to play with host memory.  The
only required synchronizations are with the device-side operations
which we perform correctly here.
This supersedes #99
> Enable async read/write ops on a separate stream.

- pygpu/gpuarray.pyx
- pygpu/tests/test_gpu_ndarray.py
We just disable pickling because we can't preserve and restore the GPU state.
> Fix pickling returning broken objects

- pygpu/gpuarray.pyx
the other nogil attribute, just tell we can call those function without having the gil, it wasn't freeing them.
This isn't finished, I just wanted to have this public to show this. We need to do this at other point.
> [MRG] Release the gil

- doc/installation.rst
- src/gpuarray_buffer_cuda.c
This functionality doesn't exist in 6.5 so we keep the old behavior for that version in order to not drop support right now.
> Create a primary context for better compat with the runtime API.

- pygpu/gpuarray.pyx
- src/CMakeLists.txt
- src/gpuarray/buffer.h
- src/gpuarray/elemwise.h
- src/gpuarray/kernel.h
- src/gpuarray/util.h
- src/gpuarray_buffer_cuda.c
- src/gpuarray_buffer_opencl.c
- src/gpuarray_elemwise.c
- src/gpuarray_kernel.c
- src/gpuarray_util.c
- src/private.h
- src/private_opencl.h
- tests/CMakeLists.txt
- tests/check_array.c
- tests/check_buffer.c
- tests/check_elemwise.c
- tests/device.c
This is a C port of the python elemwise code with dimension collapsing and broadcasting.
There are only two major kernel variants (contig and basic) for now, but it is possible to add more if required.
Also possible to add in the future are prepared calls, and direct variant calls.
> C elemwise generator

- pygpu/gpuarray.pyx
- src/gpuarray/buffer_blas.h
- src/gpuarray_array_blas.c
- src/gpuarray_blas_cuda_cublas.c
- src/gpuarray_blas_opencl_clblas.c
- src/gpuarray_buffer_cuda.c
- src/gpuarray_util.c
This implements very specialized kernels for gemvBatch and gerBatch (within a generic interface) to support the blocksparse op from Theano.
We plan to update the implementation later to support the full interface.
> Batch blas ops

- pygpu/tools.py
- src/gpuarray/array.h
- src/gpuarray_array.c
I checked we don't use *fromdata in Theano and I think I updated all use of it in libgpuarray.
Should I update one of the version?
> Change the interface of GpuArray_fromdata

- src/gpuarray/array.h
- src/gpuarray_array.c
This reverts commit 9ff5eec91f3624cdd0c7757848fa109bbfb8f8af.
This cause failure in the daily buildbot of the new back-end in Theano on the DLT.
> Revert "Make *_fromdata steal the reference to gpudata."

- src/gpuarray_buffer_cuda.c
Apparently that is what cuMemAlloc does and I read the docs wrong.
> Align allocations to 64 bytes instead of 16.

- src/gpuarray_array.c
- src/gpuarray_elemwise.c
- src/private.h
This be faster and doesn't change the public interface.
> Use 32-bit addressing in take1 when possible

- src/gpuarray_buffer_cuda.c
This will add `cuStreamDestroy(ctx->mem_s)` in `static void cuda_free_ctx(cuda_context *ctx)` as discussed [here](https://groups.google.com/forum/#!topic/theano-dev/pRuqbclL_Cw).
> Add missing cuStreamDestroy a context's memory stream

- src/gpuarray/elemwise.h
- src/gpuarray_elemwise.c
- src/gpuarray_util.c
- tests/check_elemwise.c
This enable support for float16 in elemwise operations by performing the computation in float32.
This behaviour will only be active if the GE_CONVERT_F16 flags is passed when creating the GpuElemwise object.
It does not make GPUs which don't have even the most basic support for float16 work since those don't have either the data types or the conversion primitives that we need.  On the cuda side it should mostly always work, but on OpenCL your device needs to support the cl_khr_fp16 extension (which notably NVIDIA and most CPU vendors chose not to enable).
> float16 support for  GpuElemwise

- doc/installation.rst
- setup.py
fix #194. It made me realize that we require cython 0.21 minimum to build so this updates the docs to reflect that.
> Update the cython requirement.

- pygpu/gpuarray.pxd
- pygpu/gpuarray.pyx
- src/gpuarray/buffer.h
- src/gpuarray_buffer_cuda.c
- src/gpuarray_buffer_opencl.c
- src/private_cuda.h
- src/private_opencl.h
This helps lower the overhead of cuda_wait() for the single-stream case.
> Add a shortcut to cuda_waits() in case we are on the same stream.

- pygpu/gpuarray.pyx
- pygpu/operations.py
- pygpu/tests/test_operations.py
numpy's concatenate and split allow axis to be a negative number. Since _concatenate and _split take an unsigned int, it seemed that the best place to make this change was in operations.concatenate and operations.array_split.
> allow concatenate and split to take a negative axis

- pygpu/reduction.py
- pygpu/tests/test_reduction.py
I'm unsure whether you want this, but it seems useful to me to allow a call to a ReductionKernel to take a broadcast=True argument. For example, if a = [[1,2,3]] and b = [[4,5,6], [7,8,9]], in NumPy we can write sum(a*b, axis=-1) to get [32,50], and the attached change allows a reduction kernel to do the same.
Possible issue: maybe broadcasting on the reduction axis is not useful. The attached change allows this, but maybe it should be disallowed.
> Allow reduction kernels to do broadcasting

- src/gpuarray_buffer_cuda.c
This fixes a problem with take1() and check_error=1 where the error would sometimes not be reported or reported for a subsequent call in single stream mode.
> Fix reading and writing to mapped pointers in single stream mode.

- src/gpuarray_array.c
The double free only happens when recovering from an exception.
BTW -- it appears that you can't concatenate two arrays with different contexts even if the contexts differ only in their streams. Is this by design?
Thanks!
> fix double free in GpuArray_concatenate

- src/gpuarray_buffer_opencl.c
In cl_move(), we didn't check if src and dst are the same array. If they are in fact the same array (which is allowed), clReleaseEvent() will be called twice for the same event. If the reference counter for that event happens to go 0, it will be deleted. It won't cause an immediately failure, however later clEnqueueCopyBuffer() will be using an invalid (deleted) event, and accessing memory in an unexpected manner.
In my experiments, after passing src==dst to cl_move(), the program will crash (segmentation fault) after some time in some weird places (not inside cl_move or clEnqueueCopyBuffer) with a mysterious message (like "corrupted double-linked list" in glibc, or a segmentation fault inside a completely irrelevant function). This is because clEnqueueCopyBuffer() damaged the heap …
> Check if src == dst in cl_move() and avoid double event release

- src/gpuarray_buffer_cuda.c
- src/gpuarray_buffer_opencl.c
Currently libgpuarray does not support dynamic shared (local) memory for OpenCL. Function cl_callkernel() simply returns `GA_UNSUPPORTED_ERROR` when the paremeter "shared" is non-zero. Since dynamic local memory is important to implement many kernels (like cumsum) in Theano, I am trying to add local memory support to libgpuarray and thus we can have more OpenCL functionality in Theano.
Since OpenCL needs a different syntax than CUDA for dynamic shared memory, it is not easy to implement this using libgpuarray's existing macro based "compatibility layer" for CUDA and OpenCL. In CUDA, we define a dynamic shared memory like the following:
`
extern __shared__ float shared_variable[];`
And then we give cuLauchKernel a size parameter to allocate this shared memory array.
In OpenCL, a dynamic …
> Local memory support for OpenCL kernels

- src/gpuarray_buffer_opencl.c
Before we add another flag for indicating half precision arithmetic support on Nvidia Pascal and AMD Polaris, the current flag GA_USE_HALF is used for indicating half precision load and store support and should always pass on OpenCL platforms (like what we did in the CUDA backend), because half precision load and store are part of OpenCL 1.0 specification without any extensions. This allows us to pass all libgpuarray tests on most OpenCL platforms (which do not have cl_khr_fp16), and enables some kernels in Thenao to work with OpenCL. See also issue #218 
In the long run we probably want to make GA_USE_HALF obsoleted and use flags like  GA_USE_HALF_LOADSTORE and GA_USE_HALF_MATH etc.
Without this workaround the following libgpuarry tests failed:
```
$ tests/check_elemwise 
Running …
```
> GA_USE_HALF workaround for OpenCL

- src/gpuarray_array_blas.c
- src/gpuarray_array_collectives.c
- src/gpuarray_buffer_opencl.c
In windows, python 3.4 compiled Visual Studio 2010 and it don't support C99.
This PR enable to compile libgpuarray in VS2015.
> enable to compile in under C99 compiler

- src/gpuarray_buffer_cuda.c
> Fix cuda wait for writes and reads

- src/gpuarray_buffer_cuda.c
- src/gpuarray_buffer_opencl.c
- src/private_opencl.h
The CUDA runtime constant warpSize is used in a few Theano GPU kernels. This patch defines a new preamble macro, GA_WARP_SIZE, to make kernel code portable between CUDA and OpenCL. In CUDA, it is simply replaced by warpSize; in OpenCL, no such runtime constant is provided; the closet alternative is the kernel property CL_KERNEL_PREFERRED_WORK_GROUP_SIZE_MULTIPLE. Technically there are some subtle differences between warpSize and CL_KERNEL_PREFERRED_WORK_GROUP_SIZE_MULTIPLE, however on GPUs they both reflect the hardware SIMD size. 
Since it depends on the GPU device, the definition of GA_WARP_SIZE in OpenCL preamble has to be created dynamically. I added necessary code to cl_check_extensions() that creates a dummy kernel, gets the GA_KERNEL_PROP_PREFLSIZE property and updates the …
> Add a new preamble macro GA_WARP_SIZE

- pygpu/gpuarray.pyx
- pygpu/tests/test_gpu_ndarray.py
I think I need methods to copy to and from existing buffer in a numpy array in order to minimize copies and avoid creating redundant arrays in Platoon. How does this seem?
> Add methods to read and write to/from existing ndarray in GpuArray

- src/cache/twoq.c
- src/gpuarray_buffer_cuda.c
This could lead to segfaults (most common) or silent bad results (rare, but dangerous).
> Fix problem with the kernel cache.

- src/gpuarray_array.c
If the index array passed to take1 has a dtype other than int64/ssize_t, it was returning the wrong result; this change uses whatever the index array's actual dtype is.
Thanks!
> make take1 kernel use actual typecode of ind

- src/gpuarray_buffer_opencl.c
Removed a empty definition and moved the final one further up. Not sure if this breaks anything so needs a review.
See issue #262 and also [Theano issue #4705](https://github.com/Theano/Theano/issues/4705) for a followup issue that happens after this is fixed.
> Remove string definition with no length in gpuarray_buffer_opencl, see #262

- pygpu/_elemwise.pyx
- pygpu/elemwise.py
If you forget to tag one of the arguments as either read or write, then it will be completely ignored.
> Check that arguments have some flags that apply

- src/util/integerfactoring.c
Use instead `malloc()` for systems allergic to C99 VLAs. Fixes #272 .
> Avoid using VLAs in integerfactoring.c.

- src/util/integerfactoring.c
- src/util/integerfactoring.h
- tests/check_reduction.c
- tests/check_util_integerfactoring.c
Added, for developer usage, a scheduler function that accepts `uint64_t` arguments rather than `ga_factor_list`s.
Also:
- Refactored and improved factorizer logic. In particular, always attempt an optimal 2-, 3- or 5-smooth factorization depending on `k`-smoothness constraint, instead of 2-smooth (round-up-to-next-power-of-2) only. For very large `n`, the next 5-smooth number is usually less than 1% higher. Compare to the next 2-smooth number, which can be as much as 100% higher.
- Many new testcases and extra checks for older testcases.
- Switched to >2x faster primality checker (BPSW).
- Important inline assembler bugfix, for an error causing miscompilation in Release mode.
- Renamed `gaIFLsnprintf()` to `gaIFLsprintf()` and use `sprintf()`, which is a C89 standard library function.
- …
> Internal scheduler with integer arguments + Factorizer improvements + Assorted bugfixes

- src/gpuarray_array.c
- src/gpuarray_array_blas.c
- src/gpuarray_buffer_cuda.c
- src/gpuarray_buffer_opencl.c
- src/gpuarray_util.c
Eliminated warnings:
- `-Wsign-compare`
- `-Wempty-body`
- <strike>`-Wunused-parameter`</strike>
As well, a possibly logic fault was identified in `src/gpuarray_buffer_opencl.c` involving lack of braces around the branches of an `if/else`.
GCC now builds libgpuarray almost without any warnings (the exception is `gpuarray_reduction.c`, which is the subject of another PR and separately reports under `-Wmissing-field-initializer` even though in that particular case the usage is intentional and correct).
> Eliminate nearly all GCC warnings under -Wall -Wextra -Wno-unused-parameter.

- src/gpuarray_reduction.c
- tests/check_reduction.c
This avoids an infinite loop when counting ndX downto 0 with unsigned
integers, as the condition `unsigned >= 0` always holds.
> Make MaxAndArgmax use internally signed axis numbers.

- src/gpuarray_array.c
This makes the case reported at https://github.com/Theano/Theano/issues/5154 go from 
~3.6e-2 per call to ~4.3e-4 per call on my card.
We could maybe gain a few more percent (and avoid other corner cases) with a better scheduling, but I am too tired to finish that.
> Fix for scheduling in some corner cases.

- .gitignore
- pygpu/gpuarray.pxd
- pygpu/gpuarray.pyx
- src/gpuarray/buffer.h
- src/gpuarray_buffer_cuda.c
- src/gpuarray_buffer_opencl.c
- src/private_cuda.h
**Code added to get PCI Bus ID from a CUDA device.**
Some workaround has been done to get the same thing
from OpenCL, but both OpenCL and CUDA don't print
the same info. So for the moment, getting PCI Bus ID
is available from CUDA and "not supported" for OpenCL
(see commented code (will be removed after reviewing!)).
Recall: PCI Bus ID is printed as:
```domain:bus:device.function```
where domain, bus, device and function
are hexadecimal strings:
domain: 16 bits info (4 characters)
bus: 8 bits info (2 characters)
device: 5 bits info (2 characters)
function: 3 bits info (1 character)
Reference:
http://docs.nvidia.com/cuda/cuda-runtime-api/group__CUDART__DEVICE.html#group__CUDART__DEVICE_1gea264dad3d8c4898e0b82213c0253def
http://www.makelinux.net/ldd3/chp-12-sect-1
> Code added to get PCI Bus ID from a CUDA device.

- src/gpuarray_buffer_cuda.c
- src/loaders/libcuda.fn
- src/loaders/libcuda.h
For #290.
- Now uses `cuModuleLoadDataEx` to link compiled kernel.
- Linker error during `cuModuleLoadDataEx` will be logged in the same manner as compiler error.
To test this (on linux):
1. rename `/path/to/nvidia-driver/libnvidia-ptxjitcompiler.so*` to something invalid
2. `sudo ldconfig`
3. run `check_elemwise` in C tests to see if error message pops up.
error message for me:
```
CUDA kernel link failure::
Linker error log:
fatal   : Unable to load library 'libnvidia-ptxjitcompiler.so.367.44'
```
> better error message for CUDA JIT linking

- src/gpuarray_elemwise.c
- tests/check_elemwise.c
There was an index bug which would cause the library to crash in that case.  I've fixed it and added a test for that.
> Fix call of elemwise in the basic case when using scalars.

- src/gpuarray_blas_cuda_cublas.c
- tests/CMakeLists.txt
- tests/check_blas.c
Cuda 8 added an implementation of atomicAdd for doubles so we need to mask our own.
> Fix for cuda8 in blas code.

- src/gpuarray_array.c
- tests/check_array.c
fix gh-https://github.com/Theano/Theano/issues/5285
> Add offset handling for indices and result in take1()

- pygpu/gpuarray.pxd
- pygpu/gpuarray.pyx
After fighting with kernels in cublas, and pulling my hair trying to figure out what was wrong while investigating https://github.com/Theano/Theano/issues/1168, I took a step back and timed the whole stack.
This is where I discovered that we had a huge overhead in our cython implementation of the method.  This fixes it and speeds up the __setitem__ for small cases by about 30%.
> Speedup the cython implementation of setitem.

- pygpu/gpuarray.pyx
- src/CMakeLists.txt
- src/gpuarray/buffer.h
- src/gpuarray_buffer_cuda.c
- src/gpuarray_buffer_opencl.c
Comes with a major bump since we break the interface for older clients (not that I know of any).
> Stop returning allocated memory from the library to avoid problems on windows

- src/gpuarray/config.h
This should fix the compilation errors in #317, it can get me pass the build stage at least, there're still other issues, but that's another story...
> Fix vs2013 syntax error

- src/gpuarray_buffer_opencl.c
I found that GA_DECL_SHARED_PARAM makes an error in Apple OpenCL environment.
I think it seems that this issue is caused by the array declaration not decaying into pointer.
So I modified the array declaration into pointer declaration.
> fix GA_DECL_SHARE_PARAM for apple opencl

- doc/installation.rst
This was reported in #336.  It's not really possible to fix without a rather large effort so this just adds a warning about it in the docs.
> SIP breaks library loading with system python.

- Makefile
- src/loaders/dyn_load.c
- src/loaders/dyn_load.h
- src/loaders/libcuda.c
- src/loaders/libopencl.c
The cuda drivers version 375 have some problems with the JIT that lead to bad code.
Since this is basically impossible to detect otherwise, this add a way to get the actual version of the cuda driver and blacklists bad versions.  The blacklist will need to be updated once a fixed version is released.
The last known good version is 373.06 and there are no working versions above that as far as I know, which is why the current blacklist has an open range.
> Blacklist bad versions of the cuda drivers

- src/gpuarray_array.c
This brings us in line with the behaviour of numpy 1.12 and may trigger a bit more of a speedup in some cases.
This still works with numpy 1.11.
> Change the definition of the contiguous flags to ignore strides on dimensions of size 1

- pygpu/gpuarray.pyx
- pygpu/tests/test_gpu_ndarray.py
I ran this manually plus the old getitem tests, works for me. You'll notice that I moved quite a bit of logic from `__cgetitem__` to `__getitem__` simply because I am faster when I can do this kind of stuff in Python. If you feel this is gonna cost too much efficiency (which I cannot say for sure, but probably it's no issue), you may want to push it back to C. Although that would likely mean all of it.
Closes #365
> Issue 365  getitem none

- src/gpuarray/array.h
It seems "util.h" is not automatically included when we use "array.h". I have encountered the error while trying to use `GpuArray_ITEMSIZE()`, defined in `array.h`, which uses `gpuarray_get_elsize()` defined in `util.h`.
```
/home/notoraptor/.theano/compiledir_Linux-4.4--generic-x86_64-with-debian-stretch-sid-x86_64-2.7.13-64/tmpQo9Y8T/mod.cpp: In member function ‘int {anonymous}::__struct_compiled_op_7cd93cb03039f5356757163adef008af::run()’:
/home/notoraptor/.local/include/gpuarray/array.h:197:63: error: ‘gpuarray_get_elsize’ was not declared in this scope
#define GpuArray_ITEMSIZE(a) gpuarray_get_elsize((a)->typecode)
^
```
This PR add the missing inclusion in `array.h`.
@abergeron
> Include "util.h" in "array.h".

- src/gpuarray_array.c
- src/gpuarray_array_blas.c
- src/gpuarray_blas_cuda_cublas.c
- tests/check_blas.c
Fixes https://github.com/Theano/Theano/issues/5795
> Fix contiguous detection to properly handle F-contiguous input.

- .gitignore
- src/cache/disk.c
- src/gpuarray_elemwise.c
- src/loaders/dyn_load.c
- src/util/error.c
- src/util/error.h
The last master version of libgpuarray fails to compile on Windows 8.1 64 bits for Python 2.7 with Microsoft C++ Compiler 2008. This PR tries to fix all errors I have found. **Not yet tested on Linux**.
@abergeron @nouiz
> Try to fix compilation errors on Windows/Python 2.7/64 bits.

- .gitignore
- doc/c_api/file/error_8h.rst
- src/gpuarray/error.h
I'm still not sure why "duplicate ID" warnings show up in the Linux VMs, but not the MacOS one.
> Fix sphinx warnings

- src/gpuarray_collectives_cuda_nccl.c
> Fix float 16 for cuda collectives

- CMakeLists.txt
- INSTALL
- doc/_templates/layout.html
- doc/installation.rst
- src/util/xxhash.c
- src/util/xxhash.h
Not all URLs could be converted, as there are still Web sites out there not having HTTPS set up correctly.
> Use secure HTTPS URLs where possible

- .travis.yml
- src/gpuarray_array_blas.c
This is re-applying an old fix that was in Theano, see https://github.com/Theano/Theano/blob/master/theano/tensor/blas.py#L649-L663
This first commit fixes Theano/Theano#5730, but there are many other places lda/b/c would be considered "incorrect".
Another option might be to consider the other contiguity pattern here, but I don't know how to make sure we choose the right one.
> Use "right" ld* with 1D matrices

- pygpu/blas.pyx
- pygpu/tests/test_blas.py
Basically c/p from gemm code.
In tests, I removed the cases where destination array is fortran-contiguous, because it would trigger an error at [here](https://github.com/Theano/libgpuarray/blob/master/src/gpuarray_array_blas.c#L540).
```c
cC = is_last_2d_contiguous(C);
if (!cC) {
err = GA_VALUE_ERROR;
goto cleanup;
}
```
The function `is_last_2d_contiguous` can't detect a rank-3 fortran-contiguous array. Because the least strided index would be 0 while this only test for the last two indices. For example:
```python
>>> x = np.random.rand(3,4,5).astype('float32')
>>> y = np.asfortranarray(x)
>>> x.strides
(80, 20, 4)
>>> y.strides
(4, 12, 48)
```
The batched gemm needs an 3d array with the 2nd stride being 4, so it's neither c-contig or f-contig as whole. I'm not sure what's the most …
> python interface for rgemmBatch_3d

- pygpu/_elemwise.pyx
- pygpu/elemwise.py
- pygpu/gpuarray.pyx
- src/gpuarray_buffer_opencl.c
- src/gpuarray_collectives_cuda_nccl.c
Some accumulated small fixes.  Most notably float16 is changed to a struct to avoid bad results.
> Mixed fixes

- src/gpuarray_array_blas.c
With my intentionally-severe
CMAKE_C_FLAGS='-Wall -Wextra -Wno-unused-parameter -Wno-missing-field-initializers -std=gnu89 -Wpedantic'
and GCC 6.2.1, I get very few warnings (Yay!) but those that remain are persistent and annoying. Silence them.
- First, a case where a signed and unsigned value are compared for inequality.
- Second, three cases where a comparison for typecode inequality with itself (???) was being done.
> [Trivial] Silence Warnings

- src/gpuarray_buffer_cuda.c
As discussed in https://github.com/Theano/Theano/issues/5706, this PR changes the CUDA host/device synchronization to use blocking synchronization instead of yielding when configured for multi-threading (e.g., when `gpuarray.sched=multi` in Theano). This lowers CPU utilization and power consumption by a large margin while the CPU is waiting for the GPU.
The alternative would be to introduce a third option so one could select between spinning (the current default), yielding and blocking, but in https://github.com/Theano/Theano/issues/5706 we figured that yielding may not be that useful anyway.
Closes https://github.com/Theano/Theano/issues/5706. (Not sure if that works across project boundaries? Probably not.)
> Use blocking_sync instead of yield when configured for multi-threading

- pygpu/gpuarray.pyx
- src/gpuarray_array.c
- src/gpuarray_array_blas.c
- src/gpuarray_array_collectives.c
- src/gpuarray_blas_cuda_cublas.c
- src/gpuarray_buffer.c
- src/gpuarray_buffer_collectives.c
- src/gpuarray_buffer_cuda.c
- src/gpuarray_buffer_opencl.c
- src/gpuarray_elemwise.c
- src/gpuarray_kernel.c
> Add all the missing error messages and stop filtering in pygpu.

- pygpu/basic.py
- pygpu/gpuarray.pyx
- src/gpuarray_array.c
Adds an offset to all GpuArrays in DEBUG to help catch errors where the offset is not handled appropriately.
Also fix the meaning of .gpudata/.data/.base_data to better emulate what PyCUDA/PyOpenCL does.
> Add offset in DEBUG

- pygpu/gpuarray.pyx
fix regression reported in https://github.com/Theano/libgpuarray/pull/449/files/e2f1f07accad1561db8177d85f119dfd3bcdfa2a#diff-ff48e8755d3dfca5cabbf877f62ff560
> Restore the IndexError in pygpu_index.

- tests/CMakeLists.txt
Also modified the fall-back code to
- check for the availability of the required libraries: lpthread, lrt and lm
- link to these libraries.
> Added fix to detect 'check' version using pkg-config.

- src/gpuarray_buffer_cuda.c
- src/loaders/libcublas.c
- src/loaders/libnvrtc.c
Fix #472 . Tested on my Windows 8.1 64 bits with Python 2.7.13 Anaconda 64 bits.
When compiled as Debug version:
```
(python2) HPPC@NOTORAPTOR-HP C:\Users\HPPC\mila\dev\git\theano
> echo %THEANO_FLAGS%
device=cuda0
(python2) HPPC@NOTORAPTOR-HP C:\Users\HPPC\mila\dev\git\theano
> python -c "import theano"
ERROR 18: Could not load "nvrtc64_90.dll": Le module spécifié est introuvable.
Detected CUDA 8.0.
Loading cuBLAS 8.0.
Using cuDNN version 6020 on context None
Mapped name None to device cuda0: GeForce 840M (0000:0A:00.0)
```
@nouiz @abergeron @lamblin .
> Loop over supported CUDA versions to find installed CUDA on Windows and Mac.

- src/gpuarray_buffer.c
- src/gpuarray_elemwise.c
This fixes a problem that would make GpuKernel_init() segfault when there was an error creating the kernel.
This was exacerbated by the fact that Theano 0.9 will try to precompile kernels to binary and load them back which isn't supported anymore, and would trigger an error.
> Fix segfault in Theano 0.9

- src/cache/lru.c
- src/cache/twoq.c
- src/gpuarray_buffer_opencl.c
- src/gpuarray_elemwise.c
- src/util/integerfactoring.c
A compiler error fix for #481, plus many errors reported when `-Wall -Wextra` is in use, including all the errors [here](https://buildd.debian.org/status/fetch.php?pkg=libgpuarray&arch=i386&ver=0.6.8-1&stamp=1500376646&raw=0).
Note that certain warnings appear only at `-O0` and some only at `-O2`, so it's important to build in both release and debug mode to see fresh warnings.
> Trivial Fixes related to #481.

- CMakeLists.txt
- tests/check_buffer_collectives.c
- tests/check_collectives.c
- tests/check_elemwise.c
- tests/check_reduction.c
- tests/communicator.c
- tests/main.c
Issue #481 brought to the fore the problem that our compiler flags are not as strict as Debian's. My PR #483 solved both an error and most compiler warnings under the Debian flags.
The one remaining flag that gave us grief was `-Wdeclaration-after-statement`, which essentially enforces the C90 requirement (imposed upon us by MSVC) of all declarations being upfront in a scope. All files in the codebase except those under `tests/` were already `-Wdeclaration-after-statement`-clean; This PR makes the remainder `-Wdeclaration-after-statement`-clean as well.
The entire codebase as I can build it on my machine (OpenMPI & CUDA enabled) now compiles with **NO** warnings or errors with the following flags on GCC 6.2.1:
-Wall
-Wextra
-Wno-unused-parameter
-Werror=format-security
-Wdate-time …
> Muzzle -Wdeclaration-after-statement and upgrade warning flag strictness

- pygpu/_elemwise.pyx
- src/gpuarray/elemwise.h
- src/gpuarray_elemwise.c
- tests/check_elemwise.c
No tests yet, but it seems to solve an issue in Theano with GpuIncSubtensor.
> Implicitly left-pad with broadcastable dims

- src/gpuarray_collectives_cuda_nccl.c
- src/loaders/libnccl.c
- src/loaders/libnccl.fn
- src/loaders/libnccl.h
Extracted from #485.
fix https://github.com/Theano/libgpuarray/issues/497
> Upgrade bindings to nccl 2.0

- src/gpuarray_blas_cuda_cublas.c
On my computer, this seems to fix errors reported here: http://earlgrey.iro.umontreal.ca:8080/job/Theano_pr_win/44/
Parameter `A` for `sgerBatch` should be the one that is read and written, but current code call `cuda_record` to that parameter with flag `CUDA_WAIT_READ`. This PR fixes it.
NB: I have not applied the fix to the other similar functions (e.g. `dgerBatch`, etc.), I prefer post the PR first, so that we can discuss about the problems. If it is really the right error, then I will fix it in the other functions.
@nouiz @abergeron @lamblin
> Try to fix theano error related to sgerBatch.

- conda/pygpu/meta.yaml
- versioneer.py
Let's see if appveyor generates the right version number for pygpu with this fix.
@abergeron
> Test another possible fix for versionning

- src/gpuarray_array_blas.c
fixing gpuarray_array_blas.c, C_OFFSET value comparison with NULL, fixing GpuArrayException: ('malloc: Resource temporarily unavailable', 6) @shawntan @obilaniu
> Fixing src/gpuarray_array_blas.c

- src/gpuarray_blas_cuda_cublas.c
HostFromGpu -> GpuArray_read() -> gpudata_read() -> cuda_read() -> cuMemcpyDtoHAsync()`returns 700 and then takes an exit path
```
Okay so after 3h of debugging, we know that in @shawntan's minimal testcase, `HostFromGpu -> GpuArray_read() -> gpudata_read() -> cuda_read() -> cuMemcpyDtoHAsync()` returns 700 and then takes an exit path that causes `GpuArray_read()` to return 3.
By @obilaniu
@shawntan @dendisuhubdy
Hey, just a random guess, should be easy to test.
Could you please, in current `master`, file `src/gpuarray_blas_cuda_cublas.c`, insert
`GA_CUDA_EXIT_ON_ERROR(ctx, cuda_wait(Ta, CUDA_WAIT_ALL));`
_immediately before_ the call to `cublasSgemmBatched()` at line 855 and `cublasDgemmBatched()` at line 982?
I can see a potential failure to upload the pointers "in time" on stream …
```
> CUDA race conditions 

- tests/check_elemwise.c
Fixes failure when trying to write 12B to 8B buffer
Signed-off-by: Jan Vesely <jan.vesely@rutgers.edu>
> check_elemwise: Fix array size.

- src/gpuarray_buffer_cuda.c
With the last CUDA SDK and cuDriverGetVersion, I get major=9 and minor=1 but nvrtc64_91.dll does not exist. It is still nvrtc64_90.dll. So the code fails to load the lib and look for other versions and CUDA 9 was not in the list. Now it is.
> add CUDA 9 version when trying to load libnvrtc

- .travis.yml
- src/gpuarray_buffer_cuda.c
This is the only change required to support cuda 9.1.  It's mostly a bugfix release with regards to 9.0.
> Add 9.1 to the list of versions that windows looks for.

- pygpu/tests/test_gpu_ndarray.py
Fixes #491
Signed-off-by: Jan Vesely <jan.vesely@rutgers.edu>
> pygpu/tests: Skip tests that require CUDA context if the context is not CUDA

- pygpu/gpuarray.pyx
- src/gpuarray_blas_cuda_cublas.c
- src/gpuarray_blas_opencl_clblas.c
- src/gpuarray_blas_opencl_clblast.c
- src/gpuarray_buffer_opencl.c
cl_property uses a size_t to request some clGetDeviceInfo memory sizes that are actually cl_ulong (always 64 bit).  On systems where size_t is 32 bit, this fails with CL_INVALID_VALUE (#581 reports this from ARM, but it can also happen on 32 bit x86).
This fix clips the values to fit in a size_t to avoid breaking ABI, but it might actually be better to switch to returning a cl_ulong.
The other commit is some spelling errors mostly found by Debian's lintian.
> Fix 581 (crash on 32bit) + spelling fixes

- pygpu/_elemwise.pyx
- pygpu/basic.py
- pygpu/tests/test_basic.py
- pygpu/tests/test_blas.py
- pygpu/tests/test_elemwise.py
- pygpu/tests/test_reduction.py
- pygpu/tools.py
- src/gpuarray_blas_opencl_clblas.c
- src/gpuarray_buffer_opencl.c
i.e. one that actually says that, not a generic "Could not initialize C GpuElemwise instance" or a code that means nothing until looked up.
Also extend "unsupported = skip, not fail" to all tests that use double precision.
There are two places where this reads error message text to determine the error type because the error code isn't passed up the stack: making it be so passed would be more robust, but more interface-breaking.
Motivation / testing note: Intel integrated GPUs are probably the most readily available "no double precision" hardware (the [beignet-opencl-icd](https://packages.debian.org/unstable/beignet-opencl-icd) driver disables it by default on all of them, I think Ivybridge/Haswell lack it at the hardware level).  Unfortunately, they may crash in the BLAS tests (with or …
> Give a user-friendly error when double precision is not supported
