doc/installation.rst
pygpu/dtypes.py
pygpu/elemwise.py
pygpu/operations.py
pygpu/reduction.py
pygpu/tests/main.py
pygpu/tools.py
src/gpuarray_buffer_cuda.c

There are also a couple of changes to make the code more amenable to running on python 3.

Fix problem with extcopy on Titan X

---

pygpu/elemwise.py
pygpu/reduction.py
pygpu/tests/test_elemwise.py
pygpu/tests/test_tools.py
pygpu/tools.py

Small cleanups in check_args()

---

pygpu/elemwise.py
pygpu/reduction.py
pygpu/tools.py

Follow-up to issue #66.
fix gh-66

add lru_cache as alternative to lfu_cache

---

pygpu/elemwise.py

As requested by @abergeron in PR #71

Do not generate unused variable declarations.

---

src/gpuarray_blas_opencl_clblas.c
src/gpuarray_buffer_opencl.c

Starting work on the Theano OpenCL support. Initially studying the Blas files and figuring out the C code, before starting to work on the Ops.

OpenCL Support for Theano's libgpuarray

---

pygpu/tests/support.py
pygpu/tests/test_elemwise.py
pygpu/tests/test_gpu_ndarray.py
src/gpuarray_array.c

Update for NumPy 1.10

---

doc/installation.rst
src/CMakeLists.txt
src/gpuarray_buffer_cuda.c

This works for 6.5, 7.0 and 7.5.  I still have to test for 6.0, but I hope it will work as-is.
Fixes #107

Fix PTX version.

---

pygpu/gpuarray.pyx

Add very simple str and repr for now so it becomes easier to visualize data.

ENH: add simple str and repr to gpuarray

---

src/gpuarray/util.h
src/gpuarray_util.c
tests/check_util.c

Add a C API to do dimension collapsing for elemwise (and maybe reduction too).

C collapse

---

.gitignore
setup.py
src/cache.h
src/cache/lru.c
src/cache/twoq.c
src/gpuarray/array.h
src/gpuarray/config.h
src/gpuarray/wincompat/stdint.h
src/gpuarray_array.c
src/private_config.h.in

This is very hacky atm, but could perhaps use some input. Some things left to do:

Windows fixes

---

src/gpuarray/buffer.h
src/gpuarray_buffer_cuda.c
src/gpuarray_buffer_opencl.c
src/gpuarray_util.c

This is the base to eventually have transparent support for storage-only or full float16.

Native f16

---

doc/installation.rst
src/gpuarray/array.h
src/gpuarray_array.c

fix https://github.com/Theano/Theano/issues/4318

Fix Memory leak

---

src/gpuarray_elemwise.c
tests/check_elemwise.c

This has now resurged because of the call32 option.

Work around the 32-bit signed /  64-bit unsigned bug in CUDA.

---

src/gpuarray_elemwise.c

This should update the call32 interface correctly, I'll slip in the change to preallocate the necessary buffers for collapsing tomorrow.

Update the call32 mode of GpuElemwise to have the same kernel interface.

---

pygpu/gpuarray.pxd
pygpu/gpuarray.pyx
pygpu/tests/test_gpu_ndarray.py

I just realized that this is missing.

Add take1() to GpuArray.

---

src/gpuarray_buffer_cuda.c
src/private_cuda.h

fix https://github.com/Theano/Theano/issues/4635

Fix bug in synchronization logic for multi-gpu.

---

src/CMakeLists.txt

Fix cmake not detecting sgemmEx.

---

pygpu/collectives.pxd
pygpu/collectives.pyx
pygpu/gpuarray.pxd
pygpu/tests/collectives/test_collectives.py
pygpu/tests/support.py
pygpu/tests/test_collectives.py
setup.py

Add python bindings for collevtives in pygpu

---

pygpu/gpuarray.pyx
pygpu/tests/test_gpu_ndarray.py

- Add detailed documentation in python GpuArray write and read methods

Update python GpuArray write methods to transform with asarray src

---

src/CMakeLists.txt
src/gpuarray_blas_cuda_cublas.c
src/gpuarray_buffer_cuda.c
src/gpuarray_collectives_cuda_nccl.c
src/private.h
src/private_cuda.h

Add checks to cuda_exit for cuda_waits and records

---

src/CMakeLists.txt
src/gpuarray/array.h
src/gpuarray_buffer.c
src/gpuarray_buffer_cuda.c
src/gpuarray_reduction.c
src/util/CMakeLists.txt
src/util/integerfactoring.c
src/util/integerfactoring.h
tests/CMakeLists.txt
tests/check_reduction.c
tests/check_util_integerfactoring.c

What remains incomplete is a scheduler for the kernel, as noted in the
source code.

Initial support for MaxAndArgmax and GpuArray_maxandargmax().

---

pygpu/gpuarray.pxd
pygpu/gpuarray.pyx

Follow up to #347 to restore the old API.

Make sure not to change the public cython C api.

---

src/loaders/dyn_load.c
src/loaders/dyn_load.h
src/loaders/libcuda.c

It's horrible and I really hope we never need to do that again.
We can always look at version history if it's really required.

Remove the blacklist code 

---

pygpu/__init__.py
setup.py

This should "unbreak" the commits in #388

Fix the NoseTester invocation so that it actually works now.

---

doc/_static/version_switch.js

PDF doc is not compiled right now.

remove PDF from doc version switcher

---

src/gpuarray_array.c

Add error messages in gpuarray_array.c

---

src/gpuarray_array.c
tests/CMakeLists.txt
tests/check_array.c

Fix crash in reshape.

---

pygpu/tests/main.py

Fix broken pygpu.test()

---

.appveyor.yml
release.txt

This will hopefully prevent us from shipping a version that doesn't build on windows every couple of releases.

Test the build on windows

---

CMakeLists.txt
cmake_uninstall.cmake.in

Added `make uninstall` option for `cmake`.

Add make uninstall for cmake.

---

src/gpuarray_buffer_cuda.c

This should fix the problem that if you compile multiple kernels from the same source you will only get the first one back.

Fix kernel cache

---

pygpu/gpuarray.pyx

Stop comparing to None or Ellipsis with '==' (or equivalent)

---

pygpu/gpuarray.pyx
src/cache/disk.c
src/gpuarray_buffer_cuda.c
src/gpuarray_elemwise.c

Related to https://github.com/Theano/Theano/issues/6162 .
@nouiz @abergeron

Fix some memory leaks in libgpuarray

---

src/gpuarray_blas_cuda_cublas.c
src/gpuarray_buffer_cuda.c

Follow-up to #528.  Thanks for finding these things.

Fix potential race conditions

---

src/gpuarray_buffer_opencl.c

If the provided size is < the actual string size clGetDeviceInfo() returns CL_INVALID_VALUE (see OpenCL 1.2 ch. 4.2)
Signed-off-by: Jan Vesely <jan.vesely@rutgers.edu>

opencl: Query device version string length before querying device version

---

src/gpuarray_buffer.c

This fix a bug in device detection when using opencl backend.
@abergeron @nouiz

Fix device number formatting for OpenCL.

---

src/gpuarray_blas_cuda_cublas.c

Add possible cause for the Library not initialized error message from cublas

---

pygpu/basic.py
pygpu/tests/test_basic.py

add float64 support to pygpu tril() triu()
they are used in https://github.com/Theano/Theano/blob/master/theano/gpuarray/linalg.py

add float64 support to tril triu

---

src/gpuarray_buffer_cuda.c

Also make sure to not always report errors for nvrtc64_70

Support more recent cuda versions 

---

pygpu/tests/test_blas.py
pygpu/tools.py
src/gpuarray_blas_opencl_clblas.c
src/gpuarray_buffer_opencl.c

Two crashes/exceptions, an intermittent test failure, a typo, and a code to user-friendly error table that wasn't actually being used: see commit messages for details.

Miscellaneous bug fixes (including a stack smashing crash)
